sudo: false
language: node_js
cache: yarn
notifications:
  email: false
branches:
  only: master
node_js:
  - '8'
install: yarn install
script:
  - npm run build
after_success:
  - npm run semantic-release
